// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bdigne_api.Db;

#nullable disable

namespace bdigne_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240913084929_SeedUserData")]
    partial class SeedUserData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bdigne_api.Db.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            Password = "AdminPass123",
                            Role = 0,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "dev1@example.com",
                            Password = "DevPass123",
                            Role = 1,
                            UserName = "dev1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "dev2@example.com",
                            Password = "DevPass123",
                            Role = 1,
                            UserName = "dev2"
                        },
                        new
                        {
                            Id = 4,
                            Email = "dev3@example.com",
                            Password = "DevPass123",
                            Role = 1,
                            UserName = "dev3"
                        },
                        new
                        {
                            Id = 5,
                            Email = "dev4@example.com",
                            Password = "DevPass123",
                            Role = 1,
                            UserName = "dev4"
                        },
                        new
                        {
                            Id = 6,
                            Email = "dev5@example.com",
                            Password = "DevPass123",
                            Role = 1,
                            UserName = "dev5"
                        },
                        new
                        {
                            Id = 7,
                            Email = "pm1@example.com",
                            Password = "PmPass123",
                            Role = 2,
                            UserName = "pm1"
                        },
                        new
                        {
                            Id = 8,
                            Email = "pm2@example.com",
                            Password = "PmPass123",
                            Role = 2,
                            UserName = "pm2"
                        },
                        new
                        {
                            Id = 9,
                            Email = "pm3@example.com",
                            Password = "PmPass123",
                            Role = 2,
                            UserName = "pm3"
                        },
                        new
                        {
                            Id = 10,
                            Email = "pm4@example.com",
                            Password = "PmPass123",
                            Role = 2,
                            UserName = "pm4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
