FROM node:16 AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install
COPY . .
COPY .env .env
RUN npm run build

# Serve Quasar App Nginx
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist/spa ./
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


# Minimal Dockerfile for testing
# FROM node:16
# WORKDIR /webapp
# RUN echo "Dockerfile is working!"

